app_version: 1.0.0
capabilities:
- description: ParsonLabs Music needs to manage files
  name: CHOWN
- description: ParsonLabs Music needs file permissions
  name: DAC_OVERRIDE
- description: ParsonLabs Music needs process management
  name: KILL
- description: ParsonLabs Music needs user management
  name: SETUID
- description: ParsonLabs Music needs group management
  name: SETGID

categories:
- media
- entertainment

description: ParsonLabs Music - A self-hosted music streaming service
home: https://github.com/WillKirkmanM/music

host_mounts: []

icon: https://avatars.githubusercontent.com/u/138057124?s=200&v=4

keywords:
- music
- streaming
- media
- spotify
- youtube
- entertainment

lib_version: 2.0.23
lib_version_hash: 8909de0f230ddb07f219f65eb8e67f9b8a112e9c310bee801834248854aa91af

maintainers:
- email: will@parsonlabs.com
  name: William Kirkman-Moller
  url: https://github.com/WillKirkmanM

name: parsonlabs-music

run_as_context:
- description: ParsonLabs Music runs as non-root user
  gid: 568
  group_name: music
  uid: 568
  user_name: music

screenshots:
- https://github.com/user-attachments/assets/6e905e19-aca6-408e-a117-c077bf2be8e4
- https://github.com/user-attachments/assets/24260d6e-fd56-4df5-86da-3f9cdf925611
- https://github.com/user-attachments/assets/dc913ca6-df90-40ea-9025-1180bb60655f
- https://github.com/user-attachments/assets/8af6d273-a61c-496d-9f11-a87d2d902ab5
- https://github.com/user-attachments/assets/09974ffa-7ea6-483a-aaa8-0f86ffff078a
- https://github.com/user-attachments/assets/7c19b7db-f427-4864-899a-0cb42aa3ea82
- https://github.com/user-attachments/assets/a72c56f3-a5fa-4c07-9f99-045c9648a46a
- https://github.com/user-attachments/assets/9c85421f-a96a-42ae-9747-7efc23c6bd16
- https://github.com/user-attachments/assets/398a49fd-a569-480f-89b5-0c57f73b526f
- https://github.com/user-attachments/assets/b5b012e3-7e91-4a33-b932-a04d68d14aee
- https://github.com/user-attachments/assets/e00e86f8-1bf5-4070-a2ab-f2fa79d0fcec
- https://github.com/user-attachments/assets/3471f42f-e476-4069-ac9c-0b150332b950
- https://github.com/user-attachments/assets/996d0285-cf17-4e07-98fc-f6bf482308f1
- https://github.com/user-attachments/assets/ecbecfc3-4f97-4cfc-9127-f8479d235ab8
- https://github.com/user-attachments/assets/b84e3dfe-5fe3-412c-b151-4c027ee23782
- https://github.com/user-attachments/assets/87dfe43e-c5c3-4058-a6e7-4dbb2ab8f8c6
- https://github.com/user-attachments/assets/71a8a3c0-4069-4617-b2fc-518fb095a05c
- https://github.com/user-attachments/assets/0fa243ad-da6a-4e46-a561-71636ad7a712
- https://github.com/WillKirkmanM/music/assets/98240335/7aa78513-03c9-4ee0-912c-f5dfc816247b
- https://github.com/WillKirkmanM/music/assets/98240335/76d1c540-d5cd-4ab0-9ecf-7986e0d84e31
- https://github.com/WillKirkmanM/music/assets/98240335/3b99a0c6-640e-4f38-918f-956a3ad0fd25
- https://github.com/WillKirkmanM/music/assets/98240335/ee6319a1-1b7d-4896-86b6-5a886234e2b5

sources:
- https://github.com/willkirkmanm/music

title: ParsonLabs Music
train: community
version: 1.0.0