app_version: 1.0.1
capabilities: []
categories:
- media
changelog_url: https://github.com/ParsonLabs/Parson/releases
date_added: '2026-07-30'
description: Parson is a local-first music app for your own collection.
home: https://parson.dev
host_mounts: []
icon: https://media.sys.truenas.net/apps/parson/icons/icon.svg
keywords:
- audio
- media
- music
- self-hosted
- streaming
lib_version: 2.3.15
lib_version_hash: 418b1697e018a564438ced4d735f4ced3ea16cc9fa74971a6040e769c80a66e5
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: parson
run_as_context:
- description: Container [parson] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/parson/screenshots/screenshot1.png
sources:
- https://apps.truenas.com/catalog/parson_community/
- https://github.com/ParsonLabs/Parson
- https://ghcr.io/parsonlabs/parson
title: Parson
train: community
version: 1.0.0
