resources:
  limits:
    cpus: 2.0
    memory: 4096

music:
  additional_envs: []

network:
  host_network: false
  web_port: 1993

ix_volumes:
  config: /ParsonLabsMusic
  music: /music

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: parsonlabs_music_config
      create_host_path: true
      mount_point: /ParsonLabsMusic
  music:
    type: ix_volume
    ix_volume_config:
      dataset_name: parsonlabs_music
      create_host_path: true
      mount_point: /music