app_version: v1.76.6
capabilities:
- description: Able to perform various network-related operations.
  name: NET_ADMIN
- description: Able to bind to a privileged port.
  name: NET_RAW
- description: Able to load kernel modules.
  name: SYS_MODULE
- description: Able to chown files.
  name: CHOWN
- description: Able to bypass permission checks for it's sub-processes.
  name: FOWNER
- description: Able to bypass permission checks.
  name: DAC_OVERRIDE
categories:
- networking
description: iX Support Remote Assistance
home: https://truenas.com/
host_mounts:
- description: Network device
  host_path: /dev/net/tun
icon: https://media.sys.truenas.net/apps/ix-chart/icons/icon.webp
keywords:
- vpn
lib_version: 2.0.24
lib_version_hash: 283cc9c5d0a45474968e1280324fab8fc7e176c41fdafdb6dcf9b9a74efebb9c
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: ix-remote-assist
run_as_context:
- description: Runs as a root user.
  gid: 0
  group_name: root
  uid: 0
  user_name: root
screenshots: []
sources:
- https://truenas.com/
- https://hub.docker.com/r/tailscale/tailscale
title: iX Remote Assist
train: enterprise
version: 1.2.0
