images:
  image:
    repository: tailscale/tailscale
    tag: v1.76.6

consts:
  remoteassist_container_name: ix-remote-assist
  perms_container_name: permissions
  state_path: /var/lib/tailscale
  reserved_keys:
    - --advertise-exit-node
    - --hostname
    - --authkey
