remote_assist:
  auth_key: tskey-12345678901234567890123456789012

network:
  host_network: true

ix_volumes:
  state: /opt/tests/mnt/state

storage:
  state:
    type: ix_volume
    ix_volume_config:
      dataset_name: state
      create_host_path: true
