{% set tpl = ix_lib.base.render.Render(values) %}

{% set c1 = tpl.add_container("music-server", "ghcr.io/willkirkmanm/music") %}
{% do c1.set_user(values.consts.run_as_user, values.consts.run_as_group) %}

{% do c1.environment.add_env("NODE_ENV", "production") %}
{% do c1.ports.add_port(1993, 1993) %}

{% do c1.add_storage("/ParsonLabsMusic", values.storage.config) %}
{% do c1.add_storage("/music", values.storage.music) %}

{% for store in values.storage.additional_storage %}
  {% do c1.add_storage(store.mount_path, store) %}
{% endfor %}

{% do tpl.portals.add_portal({"port": 1993}) %}

{{ tpl.render() | tojson }}