resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: Etc/UTC

parson:
  library_name: Parson
  additional_envs: []

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 31993

run_as:
  user: 568
  group: 568

ix_volumes:
  data: /opt/tests/mnt/parson/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      create_host_path: true
      dataset_name: data
  music:
    type: host_path
    host_path_config:
      create_host_path: true
      path: /opt/tests/mnt/parson/music
  additional_storage:
    - type: host_path
      read_only: false
      mount_path: /music-2
      host_path_config:
        create_host_path: true
        path: /opt/tests/mnt/parson/music-2
